NO_DIR_IN_CREATE DATABASE  IF NOT EXISTS `mysql`
USE `mysql`;

DROP TABLE IF EXISTS `accounts_admin`;

DROP TABLE IF EXISTS `accounts_user`;

DROP TABLE IF EXISTS `posts`;

DROP TABLE IF EXISTS `tags`;

DROP TABLE IF EXISTS `cates`;

DROP TABLE IF EXISTS `posts_tags`;

DROP TABLE IF EXISTS `posts_cates`;

DROP TABLE IF EXISTS `pages`;

DROP TABLE IF EXISTS `pages_tags`;

DROP TABLE IF EXISTS `pages_tags`;

DROP TABLE IF EXISTS `roles`;

DROP TABLE IF EXISTS `permissions`;

DROP TABLE IF EXISTS `media`;

DROP TABLE IF EXISTS `comments`;

DROP TABLE IF EXISTS `themes`;

DROP TABLE IF EXISTS `tools`;

DROP TABLE IF EXISTS `plugins`;

DROP TABLE IF EXISTS `settings`;



DROP TABLE IF EXISTS `account_user`;